<template>
    <div id="decrease">
        <div class="tableBox">
            <ele-table :columnConfig="columnConfig" :tableData="tableData"></ele-table>
        </div>
    </div>
</template>

<script>
export default {
    data() {
        return {
            columnConfig: [
                { key: 'ind', label: '序号', type: 'index', align: 'center' },
                {
                    key: 'waybillCode',
                    label: '运单号',
                    type: 'simple',
                    align: 'center',
                    title: true,
                    display: ({ row }) => {
                        return row.arrive ? '已到达' : '<span>确认到达</span>'
                    },
                },
                {
                    key: 'waybillCode',
                    label: '运单号',
                    type: 'simple',
                    align: 'center',
                    display: () => {
                        return '<i class="iconfont icon-feijia"></i>'
                    },
                },
                {
                    key: 'waybillCode',
                    label: '运单号',
                    type: 'button',
                    align: 'center',
                    display: () => {
                        return '<i class="iconfont icon-feijia"></i>'
                    },
                    click: (scope) => [console.log(data)],
                },
                {
                    key: 'number',
                    label: '备注',
                    type: 'simple',
                    editConfig: {
                        type: 'input',
                        switch: (r) => {
                            return true
                        },
                    },
                },
                {
                    key: '',
                    label: '操作',
                    width: '200px',
                    type: 'operate',
                    operates: [
                        {
                            type: 'button',
                            value: '确认到达',
                            display: (r) => (r.arrive ? '已到达' : '确认到达'),
                            disabled: (r) => (r.arrive ? true : false),
                            event: 'submit',
                        },
                        {
                            type: 'button',
                            value: '查看',
                            event: 'viewsRow',
                        },
                    ],
                },
            ],
            tableData: [
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
                {
                    waybillCode: '217-00000000',
                    des: 'bkk',
                    number: 5,
                    weight: 10,
                    specialCode: 'RLI',
                    flightDate: 1589341428610,
                    remark: '',
                },
            ],
        }
    },
    mounted() {},
    methods: {},
}
</script>
<style scoped lang="scss">
#decrease {
    .tableBox {
        width: 800px;
        height: 500px;
    }
}
</style>