
import {situationStart, situationStop,grounpStatus,getFlightDatas,transRunwayData} from "../manage/Monitor";
import Logger from "../../lib/logger";
import {checkWebsocketResponseDataFinish} from "../../lib/helper/flight";
import {values, extend,map, forEach} from 'lodash';
import SocketWrapper from "../lib/socketWrapper";
let clientObj = {};
const log = new Logger('connect.flight');
let   worker, client, ajax;
import {memoryStore} from "../../worker/lib/memoryStore";

/*
* 检查服务是否在线
* */
export const checkClient = (clientField) => {
    return new Promise((resolve) => {
        setInterval(() => {
            if (clientObj[clientField]) {
                resolve();
            }
        }, 50);
    });
};
// situation 服务的连接
const subWSEvent = () => {
    let client = clientObj.situationClient;
    //已延误池

    client.sub('/Flight/normalMonitor/delayFlight',(res)=>{

        let data=getFlightDatas(res,true)
        worker.publish('Web','poolMonitorWithRunway.table',{data:data,key:'delayFlights2'})
    });
    //快速过站池
    client.sub('/Flight/monitor/overStation',(res)=>{
        checkWebsocketResponseDataFinish().then((d)=>{
            let data=grounpStatus(res,'fastEnter','overStationStatus')
            worker.publish('Web','poolMonitorWithRunway.table',{data:data,key:'fastEnter'})
        })
    });
    //临界延误池
    client.sub('/Flight/monitor/criticalDelay',(res)=>{
         let data=grounpStatus(res,'critical','criticalDelayStatus')
          worker.publish('Web','poolMonitorWithRunway.table',{data:data,key:'critical'})
    });
    //始发航班池
    client.sub('/Flight/monitor/initialFlights',(res)=>{
        let data=getFlightDatas(res)
        worker.publish('Web','poolMonitorWithRunway.table',{data:data,key:'initialFlights2'})
    })
    //长期延误池
    client.sub('/Flight/monitor/alwaysDelay',(res)=>{
        checkWebsocketResponseDataFinish().then((d)=>{
            let data=getFlightDatas(res)
            worker.publish('Web','poolMonitorWithRunway.table',{data:data,key:'alwaysDelay'})
        })
    })
    //起飞保障池
    client.sub('/Flight/monitor/departureGuarantee',(res)=>{

        let data=getFlightDatas(res)
        worker.publish('Web','poolMonitorWithRunway.table',{data:data,key:'departGuarantee'})
    })
     //time flight
    client.sub('/Flight/monitor/queue',(res)=>{
        res = {
            normal: [
                {
                    startTimeAndEndTime: null,
                    id: null,
                    flightId: 167860032,
                    airlineCode: null,
                    iacoAirlineCode: null,
                    flightNo: 'CA4215',
                    aircraftNo: null,
                    scheduleTime: null,
                    scheduleTimeGroupBy: 'std_null',
                    estimateTime: null,
                    actualTime: null,
                    movement: 'A',
                    flightType: null,
                    flightIndicator: null,
                    aircraftType: null,
                    terminal: null,
                    sta: null,
                    staGroupBy: 'sta_null',
                    eta: 1634873458000,
                    ata: null,
                    ataGroupBy: 'ata_null',
                    std: null,
                    etd: null,
                    atd: null,
                    atdGroupBy: 'atd_null',
                    seat: null,
                    flightStatus: null,
                    flightExtStatus: null,
                    flightExtRemark: null,
                    cancelTime: null,
                    createTime: null,
                    succession: null,
                    successionFlightNo: null,
                    successionId: 0,
                    carrier: null,
                    masterFlightId: 0,
                    delay: 0,
                    estimateInSeat: null,
                    vipMark: null,
                    vipNo: 0,
                    destChangeReason: null,
                    destChangeDirection: null,
                    destChangeAirport: null,
                    returnReason: null,
                    returnCode: null,
                    landAbortedReason: null,
                    landAbortedCode: null,
                    aircraftIn: null,
                    aircraftOut: null,
                    preEtd: null,
                    preAtd: null,
                    nxtEta: null,
                    nxtAta: null,
                    keyMaintaince: null,
                    boardingTime: null,
                    associateAirport: null,
                    runway: '02',
                    runwayTime: null,
                    deleted: null,
                    delTime: null,
                    updateTime: null,
                    routers: [],
                    router: null,
                    carouselId: null,
                    gate: null,
                    allowbording: null,
                    quick: null,
                    closeDoorTime: null,
                    cargoCloseDoorTime: null,
                    ctot: null,
                    cobt: null,
                    tobt: null,
                    checkincounter: null,
                    exit: 0,
                    vtt: 0,
                    checkInQty: 0,
                    boardedQty: 0,
                    securityCheckQty: 0,
                    acdmSeat: null,
                    elecFlightStatus: null,
                    startCatering: null,
                    endCatering: null,
                    startDeicing: null,
                    endDeicing: null,
                    startRefueling: null,
                    endRefueling: null,
                    cabinDoorCloseEnd: null,
                    blockOn: null,
                    blockOff: null,
                    exot: 0,
                    arriveflightdelive: null,
                    passengerHandling: null,
                    maintanceAgent: null,
                    apronOrg: null,
                    successionAircraftNo: null,
                    blockOnStart: null,
                    blockOffEnd: null,
                    cancel: null,
                    unisysEta: null,
                    amisEta: null,
                    preStd: null,
                    nxtSta: null,
                    preScheduleTime: null,
                    contrlPoint: null,
                    fix: null,
                    contrlStatus: null,
                    boardingDuration: 0,
                    firstLuggageTime: null,
                    firstLuggageEstimateTime: null,
                    estimateBordingLength: 0,
                    estimateGuaranteeTime: null,
                    milestoneStatus: null,
                    relateTime: null,
                    spanMin: 0,
                    flightExtStatusText: null,
                    concernReason: null,
                    closeDoor: null,
                    pushOff: null,
                    inSeat: null,
                    boarding: null,
                    acarsOut: null,
                    routing: null,
                    hallway: 0,
                    city: null,
                    cityCn: null,
                    hallwayCn: null,
                    directionCount: 0,
                    directionAllCount1: 0,
                    directionAllCount2: 0,
                    standardMaintainTime: null,
                    standardTakeOffTime: null,
                },
                {
                    startTimeAndEndTime: null,
                    id: null,
                    flightId: 167860033,
                    airlineCode: null,
                    iacoAirlineCode: null,
                    flightNo: 'CA4216',
                    aircraftNo: null,
                    scheduleTime: null,
                    scheduleTimeGroupBy: 'std_null',
                    estimateTime: null,
                    actualTime: null,
                    movement: 'D',
                    flightType: null,
                    flightIndicator: null,
                    aircraftType: null,
                    terminal: null,
                    sta: null,
                    staGroupBy: 'sta_null',
                    eta: 1634873458000,
                    ata: null,
                    ataGroupBy: 'ata_null',
                    std: null,
                    etd: null,
                    atd: null,
                    atdGroupBy: 'atd_null',
                    seat: null,
                    flightStatus: null,
                    flightExtStatus: null,
                    flightExtRemark: null,
                    cancelTime: null,
                    createTime: null,
                    succession: null,
                    successionFlightNo: null,
                    successionId: 0,
                    carrier: null,
                    masterFlightId: 0,
                    delay: 0,
                    estimateInSeat: null,
                    vipMark: null,
                    vipNo: 0,
                    destChangeReason: null,
                    destChangeDirection: null,
                    destChangeAirport: null,
                    returnReason: null,
                    returnCode: null,
                    landAbortedReason: null,
                    landAbortedCode: null,
                    aircraftIn: null,
                    aircraftOut: null,
                    preEtd: null,
                    preAtd: null,
                    nxtEta: null,
                    nxtAta: null,
                    keyMaintaince: null,
                    boardingTime: null,
                    associateAirport: null,
                    runway: '02',
                    runwayTime: null,
                    deleted: null,
                    delTime: null,
                    updateTime: null,
                    routers: [],
                    router: null,
                    carouselId: null,
                    gate: null,
                    allowbording: null,
                    quick: null,
                    closeDoorTime: null,
                    cargoCloseDoorTime: null,
                    ctot: null,
                    cobt: null,
                    tobt: null,
                    checkincounter: null,
                    exit: 0,
                    vtt: 0,
                    checkInQty: 0,
                    boardedQty: 0,
                    securityCheckQty: 0,
                    acdmSeat: null,
                    elecFlightStatus: null,
                    startCatering: null,
                    endCatering: null,
                    startDeicing: null,
                    endDeicing: null,
                    startRefueling: null,
                    endRefueling: null,
                    cabinDoorCloseEnd: null,
                    blockOn: null,
                    blockOff: null,
                    exot: 0,
                    arriveflightdelive: null,
                    passengerHandling: null,
                    maintanceAgent: null,
                    apronOrg: null,
                    successionAircraftNo: null,
                    blockOnStart: null,
                    blockOffEnd: null,
                    cancel: null,
                    unisysEta: null,
                    amisEta: null,
                    preStd: null,
                    nxtSta: null,
                    preScheduleTime: null,
                    contrlPoint: null,
                    fix: null,
                    contrlStatus: null,
                    boardingDuration: 0,
                    firstLuggageTime: null,
                    firstLuggageEstimateTime: null,
                    estimateBordingLength: 0,
                    estimateGuaranteeTime: null,
                    milestoneStatus: null,
                    relateTime: null,
                    spanMin: 0,
                    flightExtStatusText: null,
                    concernReason: null,
                    closeDoor: null,
                    pushOff: null,
                    inSeat: null,
                    boarding: null,
                    acarsOut: null,
                    routing: null,
                    hallway: 0,
                    city: null,
                    cityCn: null,
                    hallwayCn: null,
                    directionCount: 0,
                    directionAllCount1: 0,
                    directionAllCount2: 0,
                    standardMaintainTime: null,
                    standardTakeOffTime: null,
                },
            ],
            delay: [
                {
                    startTimeAndEndTime: null,
                    id: null,
                    flightId: 16786000,
                    airlineCode: null,
                    iacoAirlineCode: null,
                    flightNo: 'CA4217',
                    aircraftNo: null,
                    scheduleTime: null,
                    scheduleTimeGroupBy: 'std_null',
                    estimateTime: null,
                    actualTime: null,
                    movement: 'A',
                    flightType: null,
                    flightIndicator: null,
                    aircraftType: null,
                    terminal: null,
                    sta: null,
                    staGroupBy: 'sta_null',
                    eta: 1634873458000,
                    ata: null,
                    ataGroupBy: 'ata_null',
                    std: null,
                    etd: null,
                    atd: null,
                    atdGroupBy: 'atd_null',
                    seat: null,
                    flightStatus: null,
                    flightExtStatus: null,
                    flightExtRemark: null,
                    cancelTime: null,
                    createTime: null,
                    succession: null,
                    successionFlightNo: null,
                    successionId: 0,
                    carrier: null,
                    masterFlightId: 0,
                    delay: 0,
                    estimateInSeat: null,
                    vipMark: null,
                    vipNo: 0,
                    destChangeReason: null,
                    destChangeDirection: null,
                    destChangeAirport: null,
                    returnReason: null,
                    returnCode: null,
                    landAbortedReason: null,
                    landAbortedCode: null,
                    aircraftIn: null,
                    aircraftOut: null,
                    preEtd: null,
                    preAtd: null,
                    nxtEta: null,
                    nxtAta: null,
                    keyMaintaince: null,
                    boardingTime: null,
                    associateAirport: null,
                    runway: '02',
                    runwayTime: null,
                    deleted: null,
                    delTime: null,
                    updateTime: null,
                    routers: [],
                    router: null,
                    carouselId: null,
                    gate: null,
                    allowbording: null,
                    quick: null,
                    closeDoorTime: null,
                    cargoCloseDoorTime: null,
                    ctot: null,
                    cobt: null,
                    tobt: null,
                    checkincounter: null,
                    exit: 0,
                    vtt: 0,
                    checkInQty: 0,
                    boardedQty: 0,
                    securityCheckQty: 0,
                    acdmSeat: null,
                    elecFlightStatus: null,
                    startCatering: null,
                    endCatering: null,
                    startDeicing: null,
                    endDeicing: null,
                    startRefueling: null,
                    endRefueling: null,
                    cabinDoorCloseEnd: null,
                    blockOn: null,
                    blockOff: null,
                    exot: 0,
                    arriveflightdelive: null,
                    passengerHandling: null,
                    maintanceAgent: null,
                    apronOrg: null,
                    successionAircraftNo: null,
                    blockOnStart: null,
                    blockOffEnd: null,
                    cancel: null,
                    unisysEta: null,
                    amisEta: null,
                    preStd: null,
                    nxtSta: null,
                    preScheduleTime: null,
                    contrlPoint: null,
                    fix: null,
                    contrlStatus: null,
                    boardingDuration: 0,
                    firstLuggageTime: null,
                    firstLuggageEstimateTime: null,
                    estimateBordingLength: 0,
                    estimateGuaranteeTime: null,
                    milestoneStatus: null,
                    relateTime: null,
                    spanMin: 0,
                    flightExtStatusText: null,
                    concernReason: null,
                    closeDoor: null,
                    pushOff: null,
                    inSeat: null,
                    boarding: null,
                    acarsOut: null,
                    routing: null,
                    hallway: 0,
                    city: null,
                    cityCn: null,
                    hallwayCn: null,
                    directionCount: 0,
                    directionAllCount1: 0,
                    directionAllCount2: 0,
                    standardMaintainTime: null,
                    standardTakeOffTime: null,
                },
                {
                    startTimeAndEndTime: null,
                    id: null,
                    flightId: 16786001,
                    airlineCode: null,
                    iacoAirlineCode: null,
                    flightNo: 'CA4218',
                    aircraftNo: null,
                    scheduleTime: null,
                    scheduleTimeGroupBy: 'std_null',
                    estimateTime: null,
                    actualTime: null,
                    movement: 'A',
                    flightType: null,
                    flightIndicator: null,
                    aircraftType: null,
                    terminal: null,
                    sta: null,
                    staGroupBy: 'sta_null',
                    eta: 1634873458000,
                    ata: null,
                    ataGroupBy: 'ata_null',
                    std: null,
                    etd: null,
                    atd: null,
                    atdGroupBy: 'atd_null',
                    seat: null,
                    flightStatus: null,
                    flightExtStatus: null,
                    flightExtRemark: null,
                    cancelTime: null,
                    createTime: null,
                    succession: null,
                    successionFlightNo: null,
                    successionId: 0,
                    carrier: null,
                    masterFlightId: 0,
                    delay: 0,
                    estimateInSeat: null,
                    vipMark: null,
                    vipNo: 0,
                    destChangeReason: null,
                    destChangeDirection: null,
                    destChangeAirport: null,
                    returnReason: null,
                    returnCode: null,
                    landAbortedReason: null,
                    landAbortedCode: null,
                    aircraftIn: null,
                    aircraftOut: null,
                    preEtd: null,
                    preAtd: null,
                    nxtEta: null,
                    nxtAta: null,
                    keyMaintaince: null,
                    boardingTime: null,
                    associateAirport: null,
                    runway: '02',
                    runwayTime: null,
                    deleted: null,
                    delTime: null,
                    updateTime: null,
                    routers: [],
                    router: null,
                    carouselId: null,
                    gate: null,
                    allowbording: null,
                    quick: null,
                    closeDoorTime: null,
                    cargoCloseDoorTime: null,
                    ctot: null,
                    cobt: null,
                    tobt: null,
                    checkincounter: null,
                    exit: 0,
                    vtt: 0,
                    checkInQty: 0,
                    boardedQty: 0,
                    securityCheckQty: 0,
                    acdmSeat: null,
                    elecFlightStatus: null,
                    startCatering: null,
                    endCatering: null,
                    startDeicing: null,
                    endDeicing: null,
                    startRefueling: null,
                    endRefueling: null,
                    cabinDoorCloseEnd: null,
                    blockOn: null,
                    blockOff: null,
                    exot: 0,
                    arriveflightdelive: null,
                    passengerHandling: null,
                    maintanceAgent: null,
                    apronOrg: null,
                    successionAircraftNo: null,
                    blockOnStart: null,
                    blockOffEnd: null,
                    cancel: null,
                    unisysEta: null,
                    amisEta: null,
                    preStd: null,
                    nxtSta: null,
                    preScheduleTime: null,
                    contrlPoint: null,
                    fix: null,
                    contrlStatus: null,
                    boardingDuration: 0,
                    firstLuggageTime: null,
                    firstLuggageEstimateTime: null,
                    estimateBordingLength: 0,
                    estimateGuaranteeTime: null,
                    milestoneStatus: null,
                    relateTime: null,
                    spanMin: 0,
                    flightExtStatusText: null,
                    concernReason: null,
                    closeDoor: null,
                    pushOff: null,
                    inSeat: null,
                    boarding: null,
                    acarsOut: null,
                    routing: null,
                    hallway: 0,
                    city: null,
                    cityCn: null,
                    hallwayCn: null,
                    directionCount: 0,
                    directionAllCount1: 0,
                    directionAllCount2: 0,
                    standardMaintainTime: null,
                    standardTakeOffTime: null,
                },
            ],
        };
        memoryStore.setItem('Pools', { monitorQueue: res })
        let data=transRunwayData(worker )
        // worker.publish('Web','monitor.queue',{data:res})
    });
    //跑道模式和禁用状态
    // client.sub('/Flight/runwayModels',(res)=>{
    //     memoryStore.setItem('Pools', { runwayModels: res })
    //
    //     let data=transRunwayData(worker )
    //     // let data=getFlightDatas(res)
    //     // worker.publish('Web','runwayModels',{data:res})
    // })

};

export const init = (worker_,httpRequest_) => {
    worker = worker_;
    ajax = httpRequest_;
    worker.subscribe('Situation.Network.Connected', (c) => {
        clientObj.situationClient = new SocketWrapper(c);
    });
    worker.subscribe('QueuesMonitor.TimeFilter', (time) => {
        transRunwayData(worker,time )
    });

    worker.subscribe('Page.poolMonitorWithRunway.Start',()=>{
        worker.publish('worker', 'Get.runway.Data')
        situationStart(worker);
        checkClient('situationClient').then(()=>{
            subWSEvent();
            console.log('situation连接成功')
        });
    });

    worker.subscribe('Page.poolMonitorWithRunway.Stop',()=>{
        situationStop(worker);
        forEach(clientObj,item=>{
             item.unSubAll()
        })
    })
};
